# Generated by Django 4.2.3 on 2023-07-14 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexerReportsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('priority_cat', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('req_depth', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('place', models.IntegerField(default=None, null=True)),
                ('spot_req_depth', models.FloatField(default=None, null=True)),
                ('ad_spots', models.IntegerField(default=None, null=True)),
                ('ad_place', models.IntegerField(default=None, null=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.indexerreports')),
            ],
        ),
    ]
