# Generated by Django 4.2.3 on 2023-07-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexerreports',
            old_name='user_id',
            new_name='user',
        ),
    ]
