# Generated by Django 4.2.3 on 2023-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_indexerreports_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerreportsdata',
            name='spot_req_depth',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
