# Generated by Django 4.2.3 on 2023-07-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_indexerreportsdata_spot_req_depth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToTest',
        ),
    ]
