# Generated by Django 4.2.3 on 2023-07-20 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_delete_totest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IndexerReports',
            },
        ),
        migrations.CreateModel(
            name='IndexerReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_cat', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('req_depth', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('place', models.IntegerField(default=None, null=True)),
                ('spot_req_depth', models.CharField(default=None, max_length=255, null=True)),
                ('ad_spots', models.IntegerField(default=None, null=True)),
                ('ad_place', models.IntegerField(default=None, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.indexerreport')),
            ],
            options={
                'verbose_name_plural': 'IndexerReportsData',
            },
        ),
        migrations.CreateModel(
            name='NmidToBeReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NmidsToBeReported',
            },
        ),
        migrations.RemoveField(
            model_name='indexerreportsdata',
            name='report_id',
        ),
        migrations.DeleteModel(
            name='IndexerReports',
        ),
        migrations.DeleteModel(
            name='IndexerReportsData',
        ),
    ]
