# Generated by Django 4.2.3 on 2023-08-02 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_indexerreport_indexerreportdata_nmidtobereported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('depth', models.IntegerField(verbose_name='Глубина')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SeoReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(verbose_name='ID товара')),
                ('keywords', models.CharField(max_length=255, verbose_name='Фраза')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
                ('req_depth', models.IntegerField(verbose_name='Глубина')),
                ('top_category', models.CharField(verbose_name='Топ категория')),
                ('reference', models.BooleanField(default=False, verbose_name='Эталон')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='services.seoreport')),
            ],
            options={
                'verbose_name': 'Сео данные',
                'verbose_name_plural': 'Сео данные',
                'ordering': ['pk'],
            },
        ),
    ]
