# Generated by Django 4.2.3 on 2023-07-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_indexerreport_indexerreportdata_nmidtobereported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySeoCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('depth', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsSeoCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(unique=True)),
                ('keywords', models.CharField(max_length=255)),
                ('frequency', models.CharField()),
                ('req_depth', models.IntegerField()),
                ('top_category', models.CharField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='services.queryseocollector')),
            ],
            options={
                'verbose_name': 'Сео данные',
                'verbose_name_plural': 'Сео данные',
            },
        ),
    ]
