# Generated by Django 4.2.3 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_queryseocollector_keywordsseocollector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryseocollector',
            name='query',
            field=models.CharField(max_length=255),
        ),
    ]
