# Generated by Django 4.2.3 on 2023-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_queryseocollector_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsseocollector',
            name='nmid',
            field=models.IntegerField(),
        ),
    ]
